# Generated by Django 4.1.2 on 2022-10-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grzyby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfShroom', models.CharField(max_length=100)),
                ('descriptionOfShroom', models.CharField(max_length=200)),
                ('picker', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(verbose_name='create time')),
                ('weightOfShroom', models.IntegerField()),
            ],
        ),
    ]
