# Generated by Django 4.1.2 on 2022-10-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grzyby', '0002_grzyby_imageofshroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grzyby',
            name='imageOfShroom',
        ),
    ]
